### PR TITLE
Get Travis CI to build on macOS and FreeBSD

### LINKED ISSUE #605: Travis CI: support for macOS and FreeBSD
Add `os: osx` and `os: freebsd` to `.travis.yml`:
[Build Environment Overview](https://docs.travis-ci.com/user/reference/overview/)

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #605.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Need to switch to the OpenSSL from Homebrew when bulding](https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892).

**Comment by DimitriPapadopoulos** [comment]
* We now attempt to build on mac0S and FreeBSD too.
* We run tests on Linux only.

By the way, do we still need to install _astyle_ ourselves? Version 3.1 has been released in 2018 and is available as a package in most Linux distributions and _Homebrew_. Even if a new version 3.2 was released I wouldn't expect it to much disruptive - we will be running `checkpatch.pl` which is more stern.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos  Wow. Thanks a lot for this work. So, we have a faster feedback if something gets broken (at least what's detectable at compile time) on all the platforms that we support.

**Comment by DimitriPapadopoulos** [comment]
Ouch! The downside is that Travis CI takes for ever to run!

Is this a temporary situation or not? Hard to tell as the only feedback is:
> **continuous-integration/travis-ci** *Expected — Waiting for status to be reported*

**Comment by mrbaseman** [comment]
this has happened to me occasionally. If I had a browser window open, it helped to navigate to travis and watch the output. If not, the only solution that I have found was to trigger another run (just update the date of the latest commit for instance) and quickly open the travis page to watch how the build proceeds :)  If you find a better way to see the details, please let me know.

**Pull request merged**
