### PR TITLE
fix (http request): pass single space as-is

### PR DESCRIPTION
**Pull request by amanjeev**
#351 : a very dumb fix.

I am sure I am not the first one to think about this but I was facing the same issue where my username at work has a space in it. I tried by passing space as-is and it actually worked for me. I could create the tunnel!

Please feel free to close etc. if need be.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
We may choose not to encode spaces if it works. Another possibility: use an alternative encoding, `%20` instead of `+`. Could you try this alternative encoding and report back?

**Comment by DimitriPapadopoulos** [comment]
All HTTP requests to the FortiGate device seem to be using the `application/x-www-form-urlencoded` media type. As far as I can tell such `GET`/`POST` requets should encode spaces using the obsolete `+` form. It could be that FortiGate devices expect the alternative `%20` form. Or maybe plain ` ` spaces.

**Comment by amanjeev** [comment]
Please see #458

**Comment by mrbaseman** [comment]
from the current perspective I believe #458 is the better solution

**Comment by amanjeev** [comment]
Please feel free to close this.

**Comment by mrbaseman** [comment]
the solution from #458 went into the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0).

**Pull request closed without merging**
