### PR TITLE
comment out line for password in config.template (fix for #507)

### PR DESCRIPTION
**Pull request by mrbaseman**

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Perhaps we should completely remove this file, or install it somewhere it doesn't get read from - for example `/usr/share/openfortivpn/config.template`. Besides I believe many setups require a personal configuration file, not a system-wide configuration file.

**Comment by DimitriPapadopoulos** [comment]
I'm also OK with this change, at least in the short term.

My only concern is that an example file should contain commented out items.

**Comment by mrbaseman** [comment]
you mean something like this?

```
# config file for openfortivpn, see man openfortivpn(1)
# host = vpn.example.org
# port = 443
# username = vpnuser
# password = VPNpassw0rd
```

**Comment by DimitriPapadopoulos** [comment]
I think we may install a version with lines commented out into `/etc/openfortivpn/config` (_sysconfdir_):
```
# config file for openfortivpn, see man openfortivpn(1)
# host = vpn.example.org
# port = 443
# username = vpnuser
# password = VPNpassw0rd
```
or a pristine version  into `/usr/share/openfortivpn/config.template` (_datadir_):
```
# config file for openfortivpn, see man openfortivpn(1)
host = vpn.example.org
port = 443
username = vpnuser
password = VPNpassw0rd
```
Or both. How would you feel about it?

**Comment by mrbaseman** [comment]
oh, you have edited [your comment](https://github.com/adrienverge/openfortivpn/pull/508#issuecomment-564926485) and added a **not** so, [both files](https://github.com/adrienverge/openfortivpn/pull/508#issuecomment-565073326), commented and uncommented would be good, maybe [like this](https://github.com/adrienverge/openfortivpn/pull/508/commits/0dac3e91ce86363c84eaaf6f253481128550dcd5) we use `sed` anyway

**Comment by DimitriPapadopoulos** [comment]
Great!

Just nitpicking here: perhaps the source version should **not** be commented because this is easier to read and maintain. If so, _sed_ should be used to add `#` in _sysconfdir_ instead of removing `#` in _datadir_.

**Comment by mrbaseman** [comment]
Ok, I can change this. One more thought as we talk about the install hook:
Uninstall doesn't remove everything. If I recall it right, the config file is not removed and maybe the example files. Should we add an uninstall hook, too, that takes care of these? And if so, how should it handle files that have been edited? I.e. remove the config file only if it contains no modifications?

**Comment by DimitriPapadopoulos** [comment]
I would uninstall the template in _datadir_ and leave the system-wide config file in _sysconfdir_. Not a big deal and probably standard practice.

**Comment by mrbaseman** [comment]
oh, that's what actually happens already. I have made the source version without comments and updated the Makefile to insert comments for the default config file.

**Comment by mrbaseman** [comment]
this fix went into [release 1.12.0](https://github.com/adrienverge/openfortivpn/releases/tag/v1.12.0)

**Pull request merged**
