### PR TITLE
Linux kernel coding style

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
* However, never break user-visible strings such as printk messages, because that breaks the ability to grep for them.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@adrienverge I have rewritten the pull request to unfold user-visible strings. Tests have been updated accordingly. Would you consider this pull request?

**Comment by adrienverge** [comment]
Thanks, you're right, it's probably better like that.

Can you put the `tests/lint/line-length.sh` change in a separated commit (for easier retrieval and understanding), and add a comment for `s/"[^"]*"/""/g` so that users can understand why we do this?
I would even break the `sed` command in two...

**Comment by DimitriPapadopoulos** [comment]
Sure. How to break the _sed_ comment in two though? Using a second temporary file - I'd rather avoid that - or a simple pipe?

**Comment by adrienverge** [comment]
I admit using a second temporary file sucks. Maybe a simple explanatory comment will be enough?

**Comment by DimitriPapadopoulos** [comment]
I have modified the pull request. Comments welcome.

**Comment by DimitriPapadopoulos** [comment]
@adrienverge Would you mind if I replaced `tests/lint/line-length.sh` with a Perl (or even Python) script? To properly handle strings, I need more elaborate code that I am unable to contribute in _awk_.

**Comment by adrienverge** [comment]
OK for Python! I'd prefer not Perl because I wouldn't be able to review it.

**Comment by DimitriPapadopoulos** [comment]
Good, I prefer Python too although Perl is handy for tiny scripts.

**Pull request merged**
