### PR TITLE
Connect to old TLSv1.0 software - override new openssl defaults.

### PR DESCRIPTION
**Pull request by ebikt**
Openssl 1.1 sets min tls version to 1.2. This prevents me to connect to fortivpn at my work.
I do not want to fiddle with system defaults, thus I added min_tls option. And then I added
seclevel-1 option, because I realised, that compiled-in list of ciphers is sufficient for me.

Inspired by similar wpa_supplicant bug, triggered by libssl1.1
  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907518#95
  https://w1.fi/cgit/hostap/commit/?id=cc9c4feccc5588137f66c40a4a6729476556853e

### CODE REVIEW

**Comment by mrbaseman** [comment]
hmm... the build fails, at least with the openssl version that travis uses. Perhaps an explicit 
`#include <openssl/ssl.h>`
is missing before including `tls1.h`

**Comment by DimitriPapadopoulos** [comment]
About this error:
```
/home/travis/.openfortivpn-deps/include/openssl/tls1.h:331:52: error: unknown type name ‘STACK_OF’
 int SSL_check_chain(SSL *s, X509 *x, EVP_PKEY *pk, STACK_OF(X509) *chain);
                                                    ^
```

This looks like an OpenSSL bug on whatever platform _travis_ use to build. Identical error in other software:
* [Issue #7314](https://freeswitch.org/jira/si/jira.issueviews:issue-html/FS-7314/) in _FreeSWICTH_.
* [Build error](https://karkhaz.github.io/tuscan/vanilla/sofia-sip.html) in _sofia_sip_.

This seems to have been fixed in _OpenSSL_ by this patch:
https://github.com/openssl/openssl/commit/e30dff9e
The best workaround is probably to precisely add the missing include directly in _config.c_:
`# include <openssl/buffer.h>`

**Comment by mrbaseman** [comment]
I have noticed that this PR has broken building against libressl, e.g. on FreeBSD. I have pushed a fix for that. From my point of view we can merge this PR now. @DimitriPapadopoulos do you have anything to add?

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Nothing to add, the part I understand looks OK to me. I suggest you merge.

**Comment by mrbaseman** [comment]
we have introduced a problem when linking against openssl 1.1.0 with this. 
TLS 1.3 is available not before 1.1.1. Fix is in #452 together with another openssl fix.

**Comment by mrbaseman** [comment]
this went into the [1.10.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.10.0).

**Pull request merged**
