### PR TITLE
fix (http request): pass single space with encoding

### PR DESCRIPTION
**Pull request by amanjeev**
Part 2 with encoding. This works too for me.

### CODE REVIEW

**Comment by cfhammill** [comment]
This fixed things for me, thanks so much!

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Martin, what is your take on this pull request? I think we should merge. Not exactly HTTP compliant but if I understand you correctly that's what FortiGate appliances are expecting.

**Comment by mrbaseman** [comment]
Yes, we have some positive feedback at least, so let's merge it. Hopefully the encoding hasn't changed between the different FortiOS versions, and if so, we have successfully tested with the recent ones.

**Comment by mrbaseman** [comment]
this went into the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0).

**Pull request merged**
