### PR TITLE
Bail out if not run as root

### LINKED ISSUE #373: Bail out if not run as root?
See latest comments in #362.

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Actual root privileges are required in many places, depending on the OS:
* On Linux, the 'noauth' option of pppd seems to require actual root privileges. Being a meber of the 'dip' group on Ubuntu is not sufficient.
* On Linux, setting routes requires root privileges unless user has CAP_NET_ADMIN capability.
* On FreeBSD, setting routes using 'route' requires root privileges.

Fixes #373.

### CODE REVIEW

**Comment by mrbaseman** [comment]
Hmm... I would merge this, but travis-ci is stuck somehow, although the commit itself seems to have passed the required check

**Comment by mrbaseman** [comment]
ok, after updating the branch travis-ci ran through smoothly

**Comment by DimitriPapadopoulos** [comment]
Not the first time travis is stuck. This seems to be happening often these days.

**Comment by mrbaseman** [comment]
I have seen it on my pull requests occasionally and there it helped to refresh the travis-ci web interface a couple of times. But I think this can do only the owner of each pull request.

**Pull request merged**
