### PR TITLE
use resolvconf if available to update resolv.conf

### PR DESCRIPTION
**Pull request by mrbaseman**
this implements the feature request from #486 and #101

### CODE REVIEW

**Comment by mrbaseman** [comment]
perhaps we first merge my other pull request and I'll rebase this one manually afterwards.
The nice thing of `resolvconf`is that it automatically merges the domain search path with an existing one (we have discussed this a bit when implementing the dns-suffix feature, but decided to start with the most simple approach).

**Comment by mrbaseman** [comment]
Just a side note: My resolvconf thinks that it should not add nameservers - but that might be due to the fact that I have a local dns resolver running on my client machine. It also doesn't take the one it receives from dhcp (which is by intention, so it might be a configuration issue of my resolvconf.d)

**Comment by mrbaseman** [comment]
I have rebased this PR on the current master branch.  I have found the reason why my resolvconf didn't update the nameservers: Like I have presumed, the reason was the following section in my `/etc/resolvconf.conf`:
```
# If you run a local name server, you should uncomment the below line and
# configure your subscribers configuration files below.
name_servers=127.0.0.1
```
If I uncomment the line with `name_servers` it correctly updates the nameservers in the resolv.conf file.

**Comment by DimitriPapadopoulos** [comment]
OK, so I guess _resolvconf_ does the right thing here.

Should we always mimic _FortiClient_ , even in this case where it might not do the right thing? What does _FortiClient_ actually do in this case? I do understand that relying on _resolvconf_ might change the behaviour of _openfortivpn_ compared to _FortiClient_ and that might be a good thing - I'm just trying to characterize this change.

**Comment by mrbaseman** [comment]
_FortiClient_ in this aspect does what _openfortivpn_ is doing currently (it just prepends search and nameservers in resolv.conf). With this change, _openfortivpn_ does use resolvconf if it is installed. If resolvconf is not available (or if its path is set to something nonexisting at configure time, i.e. `configure --with-resolvconf=/sbin/resolvconf_disabled`), _openfortivpn_ also will behave (nearly) the same way as before. It would check if an executable `/sbin/resolvconf_disabled` is there and when it notices that it's not it should fall back to the previous behavior.
I think if someone installs resolvconf, he does it for some reason, namely because he runs into trouble with the different programs (dhcp, various vpn solutions) that compete about changing resolv.conf. In that sense, I think doing something different than Forticlient it is a good move forward to provide a better user experience.

**Comment by mrbaseman** [comment]
Maybe we should update the man page and perhaps README.md and describe the change there.
Not sure about the `--help` output - perhaps just add a hint and refer to the man page?

**Comment by DimitriPapadopoulos** [comment]
Perhaps a very short hint in the `--help` summary. No need to refer to the man page or the README any more than we do now - that should be obvious.

**Comment by mrbaseman** [comment]
yes, we are anyway close to the limit of 4095 characters. I have reworked the `--help` output a bit and the man page, too. I have mentioned resolvconf in the `--help` output. I think that's more important than mentioning that the last option takes priority when `--set-dns` is used multiple times (that's something I would consider normal unless an error is reported in this case)

**Comment by mrbaseman** [comment]
At your edit of the title I've noticed I had a typo in the commit message - I've used this occasion to squash my later commits into one larger change, in the turn of the edit of the commit message

**Comment by DimitriPapadopoulos** [comment]
Looks pretty good to me. Perhaps it should be merged into _master_ for wider testing?

**Comment by mrbaseman** [comment]
Ok. Thanks for reviewing.

**Comment by DimitriPapadopoulos** [comment]
Started testing it. Noticed we have _autoconf_ options for _pppd_/_ppp_ and _netstat_ but not _resolvconf_:
```
$ ./configure --help
[...]
Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-rt_dst           disable rtentry with rt_dst testing (for linux
                          target when cross compile)
  --with-netstat          Set the path to the netstat executable on MacOSX or
                          FreeBSD
  --with-pppd             Set the path to the pppd daemon executable
  --with-ppp              Set the path to the ppp userspace client on FreeBSD
[...]
```
Shouldn't we have such an option?

**Comment by DimitriPapadopoulos** [comment]
Ah, but there is one! I'm probably not testing the proper changeset!

**Comment by DimitriPapadopoulos** [comment]
Works well on Ubuntu 18.04.
Found missing newlines in a couple sol _log_debug_ calls while testing and fixed them in #512 - yes these newlines are counter-intuitive.

**Comment by mrbaseman** [comment]
this went into [release 1.12.0](https://github.com/adrienverge/openfortivpn/releases/tag/v1.12.0), but we have a new issue #555 due to this change on Fedora, see also #556

**Pull request merged**
