### PR TITLE
openfortivpn version 1.20.0

### LINKED ISSUE #1065: openfortivpn version 1.20.0
Most important changes:
1. Fix long-standing bug https://github.com/adrienverge/openfortivpn/issues/788.
2. Fix regression in https://github.com/adrienverge/openfortivpn/commit/5574b45296e26ebdb25a8824f003d69a75b6f609, the HTTP buffer size had been decreased by mistake.
3. Simplify code by dropping support for OpenSSL < 1.0.2.

@adrienverge Would you agree to a release?

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes  #1065.

### CODE REVIEW

**Comment by adrienverge** [comment]
Thanks Dimitri. Tagged as `v1.20.0`.

**Comment by DimitriPapadopoulos** [comment]
I had forgotten to change the version number in `configure.ac`.

Sorry about that. Is it possible to merge https://github.com/adrienverge/openfortivpn/pull/1068 and re-tag? Or do we need a 1.20.1?

**Comment by adrienverge** [comment]
I believe it's better to do a 1.20.1, just in case, because I already pushed the tag. Someone, or some automatic tools, could have pull it already.

**Comment by adrienverge** [comment]
@DimitriPapadopoulos I did it in https://github.com/adrienverge/openfortivpn/pull/1069 and tagged `v1.20.1` :+1: 

(Closes #1068)

**Comment by DimitriPapadopoulos** [comment]
Thank you for taking care of this.

**Pull request merged**
