### PR TITLE
Some random fixes

### PR DESCRIPTION
**Pull request by lkundrak**
Here's a couple of commits I'd like to see in openfortivpn.

In particular, I care about the "otp" in configuration file commit. There's one bugfix that looks semi-serious.

Sorry for posting unrelated patches in a bulk -- feel free to cherry-pick at your convenience.

### CODE REVIEW

**Comment by mrbaseman** [comment]
Hi @lkundrak,
thanks for these comits. Let me comment on them to start up discussion:
* thanks for the Openssl 1.1.0 port - nice to see that it's just a few lines. I have already opened #145 for this but expected a lot more to do. This is something where we probably should have a few confirmations that it works, but I guess we are not in a hurry here. In configure.ac there is a hard-coded version check now. Your remove that with the next commit, but just in case someone wants to test this commit separately, then a modified configure script is needed, too.
* pkg-config for detecting OpenSSL: I'm a bit in a hurry and didn't test it yet: Does it provide a configure option to the user to specify a non-default location of the ssl library? That was the main reason for the lengthy autoconf macro added in #143 , but if your much more elegant solution provides the same functionality, I'm happy to merge that one
* imo. `$prefix` should default to the empty string and when evaluating `$sysconfdir` it should contain the configure option `--prefix`, or, if not supplied, just not appear there. In previous versions (before #75) openfortivpn was always looking for its configuration in /etc, regardless of the installation prefix, which was not correct behavior, too. But maybe there are still be cases left where the outcome is not what one would expect. If I recall correctly, there is also a line in the Makefile or in the headers that's fed with the result of this `eval`
* thanks for the http-fix - maybe a call to memset would be better portable?
* --otp as a config option really in a file? How would that work? It must be a file created on the fly e.g. in a ramdisk where otp from user input is filled into a template before starting up openfortivpn, right?
* about dropping -Wall and -Werror I would let the final decision up to @adrienverge

**Comment by adrienverge** [comment]
Thanks for these fixes! Can we keep `-Wall` (to report potential problem) and put `-Werror` in `make distcheck` (to ease maintainers' work)?

**Comment by lkundrak** [comment]
> thanks for the Openssl 1.1.0 port - nice to see that it's just a few lines. I have already opened #145 for this but expected a lot more to do. This is something where we probably should have a few confirmations that it works, but I guess we are not in a hurry here. In configure.ac there is a hard-coded version check now. Your remove that with the next commit, but just in case someone wants to test this commit separately, then a modified configure script is needed, too.

Well, I've tested this.

I fact, I'm a bit concerned about whether the code is correct for OpenSSL 1.0 in the first place, because [1] claims that "using a single SSL object in two threads, one each for reading and writing" is wrong, and I think that's IIRC exact
ly what openfortivpn does (?). If that is the case, then we perhaps should consider replacing the threads altogether with a poll(2) loop.

[1] https://www.openssl.org/blog/blog/2017/02/21/threads/

In any case, OpenSSL 1.1 doesn't make things any worse in this respect, regardless what the new semantics of locking is (since the important part seems to be that now OpenSSL takes care of platform native locking specifics by itself as opposed to letting the application deal with the locking primitives).

> pkg-config for detecting OpenSSL: I'm a bit in a hurry and didn't test it yet: Does it provide a configure option to the user to specify a non-default location of the ssl library? That was the main reason for the lengthy autoconf macro added in #143 , but if your much more elegant solution provides the same functionality, I'm happy to merge that one

I think it works well in such cases in general. See the remark about PKG_CONFIG_PATH in the commit message, which I believe should be used.

> imo. $prefix should default to the empty string and when evaluating $sysconfdir it should contain the configure option --prefix, or, if not supplied, just not appear there.

That's not how it works at configure time. What you say makes sense at build time.

> In previous versions (before #75) openfortivpn was always looking for its configuration in /etc, regardless of the installation prefix, which was not correct behavior, too. But maybe there are still be cases left where the outcome is not what one would expect. If I recall correctly, there is also a line in the Makefile or in the headers that's fed with the result of this eval

Yes. I'm replacing that with a -D on a command line determined at build time as opposed by a config.h #define.

> thanks for the http-fix - maybe a call to memset would be better portable?

Well, given we build with -std=gnu99 by default, so there's not much point in that. If find the initializer to look slightly better.

> --otp as a config option really in a file? How would that work? It must be a file created on the fly e.g. in a ramdisk where otp from user input is filled into a template before starting up openfortivpn, right?

Yes, precisely as you say (and as is described in the commit message). Here's the NM plugin patch: https://bugzilla.gnome.org/show_bug.cgi?id=777404

> Thanks for these fixes! Can we keep -Wall (to report potential problem) and put -Werror in make distcheck (to ease maintainers' work)?

Okay. Updating the branch soon.

**Comment by lkundrak** [comment]
Merging this now. I believe I addressed the concerns and hopefully there's nothing controversial there.

**Comment by mrbaseman** [comment]
the configure options --with-openssl and alike just introduced with #144 have been replaced by the $PKG_CONFIG_PATH now. They were introduced on request of the Homebrew maintainer [here](https://github.com/Homebrew/homebrew-core/pull/14344) - however, I fail to see where the formula makes use of this option. Maybe Homebrew is fine with pkg_config as well, or we should re-introduce the configure option again for compatibility reasons of the next release. I just did not yet merge this PR before finding this out (but maybe it's just a matter of getting a confirmation that homebrew is fine with the latest commits)

**Pull request merged**
