### PR TITLE
Mac OS X port

### PR DESCRIPTION
**Pull request by fretn**
Mac OS X port, tested on OS X 10.9 and 10.11

### CODE REVIEW

**Comment by sibela** [comment]
Hi,
 I have installed and copiled openfortivpn as you describen on mac os sierra (10.12 (16A323))
sudo openfortivpn --version
1.1.3
But, while i try to connect ; having : Could not authenticate to gateway (No cookie given). 
Could you please assist me on this issue 
Thanks & Regards 
Sibel.

sudo openfortivpn -vvv
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "XX.XX.XXX.XX"
DEBUG:  Config realm = ""
DEBUG:  Config port = "10443"
DEBUG:  Config username = "username"
DEBUG:  Config password = "********"
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.

**Comment by fretn** [comment]
on 10.12.1 beta it works without problems for me

did it work before ?

**Comment by sibela** [comment]
no , i could not make it work on sierra os never .  probably i'm doing someting wrong.

**Comment by fretn** [comment]
I mean before sierra was released

**Comment by sibela** [comment]
yes it was working correctly before sierra

**Comment by fretn** [comment]
if I have time today, i'll downgrade the test computer to mac os 10.12 and see if it works there

**Comment by sibela** [comment]
thanks in advance, if there will be new release for openfortivpn , i can install

**Comment by eblot** [comment]
Works for me on Sierra [10.12.1 (16B2555)], with SSL VPN.

Any chance to merge the latest changes from the original project?

**Comment by mrbaseman** [comment]
I have rebased this pull-request on the current master (see attached patch file, apply with `cd openfortivpn ; zcat ../apple.patch.gz | patch -p2`)
[apple.patch.gz](https://github.com/adrienverge/openfortivpn/files/581010/apple.patch.gz)

**Comment by mrbaseman** [comment]
I have rebased this pull request on the current master branch (see attached patch file, apply with `cd openfortivpn ; zcat ../apple.patch.gz | patch -p2`) [apple.patch.gz](https://github.com/adrienverge/openfortivpn/files/581039/apple.patch.gz)

**Comment by mrbaseman** [comment]
I have rebased this pull-request once again on the (now) current master (and created a separate branch for it): https://github.com/mrbaseman/openfortivpn/tree/mac-osx-port/master
Adrien, any further cleanup needed (a squash maybe...)?

**Comment by mcella** [comment]
@mrbaseman I just test your branch on OS X 10.9.5 and it works (mostly).

I tested it with two VPNs, one works perfectly but the other one caused this warning message:

`WARN: No gateway address, using interface for routing`

and this error:

```
add net XXX.XXX.XXX.XXX: Invalid argument
route: writing to routing socket: Invalid argument
```

So the interface is not being used for routing,  it seems an OSX only problem as the same VPN under linux works perfectly fine, I got it working on OSX with the following patch:

```diff
diff --git a/src/ipv4.c b/src/ipv4.c
index 4965287..7eb0463 100644
--- a/src/ipv4.c
+++ b/src/ipv4.c
@@ -278,8 +278,10 @@ static int ipv4_set_split_routes(struct tunnel *tunnel)
                route = &tunnel->ipv4.split_rt[i];
                strncpy(route_iface(route), tunnel->ppp_iface,
                        ROUTE_IFACE_LEN - 1);
-               if (route_gtw(route).s_addr == -1)
+               if (route_gtw(route).s_addr == 0) {
                        route_gtw(route).s_addr = tunnel->ipv4.ip_addr.s_addr;
+                       route->rt_flags |= RTF_GATEWAY;
+               }
                ret = ipv4_set_route(route);
                if (ret == ERR_IPV4_SEE_ERRNO && errno == EEXIST)
                        log_warn("Route to gateway exists already.\n");
```

I haven't had a lot of time to look into it, so I'm not really confident its the right thing to do in this case.

Thanks to everyone for the great work on this project!

**Comment by mcella** [comment]
This one looks better as it explicitly uses the interface (eg. ppp0) and touches only the OS X codepath:

```diff
diff --git a/src/ipv4.c b/src/ipv4.c
index 4965287..8ea394e 100644
--- a/src/ipv4.c
+++ b/src/ipv4.c
@@ -181,6 +181,9 @@ static int ipv4_set_route(struct rtentry *route)
        if (route->rt_flags & RTF_GATEWAY) {
                strcat(cmd, " ");
                strncat(cmd, inet_ntoa(route_gtw(route)), 15);
+       } else {
+               strcat(cmd, " -interface ");
+               strcat(cmd, route_iface(route));
        }

        log_debug("%s\n", cmd);
```

**Comment by mrbaseman** [comment]
@mcella: I have commited your second version of the patch to my branch
@adrienverge: shall I open a new pull request to track this?

**Comment by adrienverge** [comment]
I have to say I'm a bit reluctant to this change: I'm afraid it will break things on the Linux version (that many people use). Moreover, we don't have any automated testing and I can't test the changes myself since I don't have access to a Fortinet VPN anymore.

So, I won't merge anything unless:
- the new PR is high-quality,
- it is backward-compatible on every platform,
- someone takes care of the Mac OS port and maintains it in case of bugs.

**Comment by mrbaseman** [comment]
@adrienverge: the new code is always enclosed in `#ifdef __APPLE__ ... #endif` and other code is commented out for the OS-X branch by means of `#ifndef __APPLE__ ... #endif`. I don't think that this would break anything for Linux (except if someone has the great idea of defining the above constant on a linux host). The autoconf input is not touched by this commit. I assume autoconf somehow detects that it's running on a Mac and defines the above constant.

I can't test either, because I don't have a Mac, but I can ask a colleague of mine. 

If it helps for you I could set up a VPN account for you on my private Fortigate 60D, running the latest FortiOS 5.2. I can't give you an admin account on this device, but maybe we can discuss privately what you would need for testing.

About taking care of the Mac OS port: I can moderate an OS-X branch and check the syntax, coding style etc., and ask my colleague every now and then if he can test. Would that be enough?

**Comment by adrienverge** [comment]
@mrbaseman That sounds great. Feel free to open a new pull request so I (and others?) can review it.

**Comment by mrbaseman** [comment]
I have rebased and squashed my branch so that it is easier to review. I have opened pull request #83 for this.

**Comment by adrienverge** [comment]
@mrbaseman thanks a lot.

**Pull request closed without merging**
