### PR TITLE
preserve existing config during install, this solves #130

### PR DESCRIPTION
**Pull request by mrbaseman**
I have decided to keep the sample config file in the etc directory, but append a ".sample" extension and copy it to the right location if it doesn't exist yet. I think this is less effort than maintaining a separate path, e.g. $prefix/share/openfortivpn or so just for a single template file which contains only a few lines

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
This issue has been bothering me as well. Thank you for looking into it!

I'm not sure I understand the logic though. Can you walk me through it? My understanding is:
```
	install etc/openfortivpn/config.sample

	if $(sysconfdir)/openfortivpn/config does not exist
	then
		copy config.sample in config (⇒ both "config.sample" and "config" exist)
	else
		delete config.sample (⇒ both "config.sample" and "config" are deleted)
	endif
```
Is that correct?

**Comment by mrbaseman** [comment]
oh, yes, your understanding is **nearly** correct. The current commit works like this:
`       install etc/openfortivpn/config.sample

	if $(sysconfdir)/openfortivpn/config does not exist
	then
		copy config.sample in config (⇒ both "config.sample" and "config" exist)
	else
		delete config.sample (⇒ "config.sample" is deleted, but "config" is preserved with its previous content)
	endif`
So, I should
- either delete config.sample also when config did **not** exist in the first place (I simply should have put the `rm` after the `endif` instead into the `else` branch)
- or keep config.sample in **both** cases (so the user can have a look which entries are supposed to be in config). This option makes also sense to me (so we would just drop the `rm`)

which option would you prefer?

**Comment by DimitriPapadopoulos** [comment]
Yes, looks good:
* Always copy `config.sample`.
* Copy `config` only when it does not already exist (do not overwrite).

By the way, it looks like files such as `config.sample` often live in `/usr/share/doc` - and are sometimes named `config.template`. I can find no clear rule though. Please do as you see fit.

**Comment by mrbaseman** [comment]
I have the impression that `/usr/share/doc` is more a place for documentation which is not in man or info format. To me `/usr/share/"package"` seems to be more appropriate. I had a look at my Ubuntu installation: Some packages create even another a subdirectory "examples" or "templates" and remove the suffix. Some have a suffix ".template", some others use ".sample". 
I guess the data structure below /usr/share/ depends on many factors (history of the package, number and type of files, personal taste of the authors,...). For _openfortivpn_ I think with currently only one file the best is to put it directly to `$(prefix)/share/openfortivpn`, and you are right, there are more ".template" files below /usr than ".sample" files, so I have renamed the file in another commit.

**Comment by DimitriPapadopoulos** [comment]
Looks perfect. Thank you for looking into this.

**Comment by mrbaseman** [comment]
Thank you for your input with your comments. Four eyes always see more than two.

**Comment by mrbaseman** [comment]
I have merged this now and rebased my other branches. I hope that I didn't mess up the github repo ;-)

**Comment by adrienverge** [comment]
> I have decided to keep the sample config file in the etc directory, but append a ".sample" extension and copy it to the right location if it doesn't exist yet

Thanks, good idea!

**Pull request merged**
