### PR TITLE
fix a  possible null pointer dereference

### PR DESCRIPTION
**Pull request by mrbaseman**
reported by coverity scan (CID 359894)

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Looks good to me.

While `end2 = strstr(line, ";")` could be `NULL`, can't `end1 = strstr(line, "\r")` be `NULL` too?

**Comment by DimitriPapadopoulos** [comment]
@adrienverge Can you merge this pull request? It's an old one before Travis CI had been (hopefully) fixed.

**Comment by adrienverge** [comment]
Sure!

**Comment by mrbaseman** [comment]
> While `end2 = strstr(line, ";")` could be `NULL`, can't `end1 = strstr(line, "\r")` be `NULL` too?

@DimitriPapadopoulos yes, you are right. I have created #758 for this

**Pull request merged**
