### PR TITLE
F_OK -> X_OK

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
We need to catch as many errors as possible early,
before calling forkpty(). After the call, messages
printed to stderr will be redirected to a pseudo-
terminal and lost.

At the same time discard existing attempts to print
to stderr after calling forkpty().

Not sure I understand the ACCESS(2) man page entirely:
	The check is done using the calling process's
	real UID and GID, rather than the effective IDs
	as is done when actually attempting an operation
	(e.g., open(2)) on the file. Similarly, for the
	root user, the check uses the set of permitted
	capabilities rather than the set of effective
	capabilities; and for non-root users, the check
	uses an empty set of capabilities.
 	This allows set-user-ID programs and capability-
	endowed programs to easily determine the invoking
	user's authority. In other words, access() does
	not answer the "can I read/write/execute this
	file?" question. It answers a slightly  differ‐
	ent  question: "(assuming  I'm  a setuid binary)
	can the user who invoked me read/write/execute
	this file?", which gives set-user-ID programs
	the possibility to prevent malicious users from
	causing them to read files which users shouldn't
	be able to read.
	If the calling process is privileged (i.e., its
	real UID is zero), then an X_OK check is successful
	for a regular file if execute permission is enabled
	for any of the file owner, group, or other.

On the other hand I have checked that X_OK works on Ubuntu
16.04 where:
$ /bin/ls -l /usr/sbin/pppd
-rwsr-xr-- 1 root dip 390888 janv. 29  2016 /usr/sbin/pppd
$

### CODE REVIEW

**Comment by mrbaseman** [comment]
I think the main point is that _openfortivpn_ **is** a privileged process (you have started it with root privileges, right?) - that's why it works. 
The interesting question would be if there are cases in which X_OK would return false even if `pppd` was executable for _openfortivpn_. Without having tested it, I would assume that if you `chmod u+s _openfortivpn_` as root, and call it as a regular user, who is not in group `dip` it would probably work with F_OK, but not with X_OK. I would expect similar issues with `sudo` configurations. The calling user might be allowed to call `sudo openfortivpn` but he might not be allowed to run `pppd` directly.
Does it make sense? 
For reference: We have started discussing this a little bit in #197

**Comment by DimitriPapadopoulos** [comment]
It works for me with `sudo`- without being member of `dip`. Also as far as I can understand `sudo` is mandatory because running `/usr/sbin/pppd` is not the only requirement. See README:
> openfortivpn needs elevated privileges at three steps during tunnel set up:
> * when spawning a `/usr/sbin/pppd` process;
> * when setting IP routes through VPN (when the tunnel is up);
> * when adding nameservers to `/etc/resolv.conf` (when the tunnel is up).

**Comment by mrbaseman** [comment]
ah ok.  sudo(8):

> ...When sudo executes a command, the security policy specifies the execution
> environment for the command.  Typically, the real and effective user and
> group and IDs are set to match those of the target user, ...

so, when called with `sudo` the process is also privileged in the context of ACCESS(2)

What remains would be an _openfortivpn_ binary with SUID root premissions in conjunction with a pppd not executable by the calling user. This is a corner case that probably doesn't need to work, because as you point out, the user would anyway also need the permissions to update the routing table and to modify `/etc/resolv.conf`. On the other hand _openfortivpn_ doesn't drop privileges, so the user might gain those privileges due to the SUID bit.

Anyhow, our README suggests `sudo` rather than setting the suid bit. If not directly invoked as root, `sudo` is the better solution, since it allows more detailed configuration e.g. who is allowed to call it.

**Comment by DimitriPapadopoulos** [comment]
I have created a small test program:
```
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>

static const char pppd_path[] = "/usr/sbin/pppd";

int main(void) {
	if (access(pppd_path, X_OK) != 0)
		fprintf(stderr, "%s: %s.\n", pppd_path, strerror(errno));
}
```

**Comment by DimitriPapadopoulos** [comment]
```
$ ls -l /usr/sbin/pppd
-rwsr-xr-- 1 root dip 390888 Jan 29  2016 /usr/sbin/pppd
$ 
$ $ id
uid=12345(user) gid=12345(user) groupes=12345(user),27(sudo)
$ 
$ gcc -o test test.c
$ ls -l ./test
-rwxrwxr-x 1 user user 8848 Oct 23 18:04 ./test
$ 
$ ./test
/usr/sbin/pppd: Permission denied.
$ 
$ sudo ./test
$ 
$ sudo chown root:user ./test
$ sudo chmod u+s,g-w,o=r ./test
$ 
$ ./test 
/usr/sbin/pppd: Permission denied.
$ 
```
So indeed the test doesn't work in this corner case.

Perhaps we should drop this change and try to fix `stderr` output as suggested by the links you've reported in #210.

**Comment by DimitriPapadopoulos** [comment]
I think it's best to close this pull request and work on `stderr` output in #201 , both if `execv()` fails or if it succeeds but `/usr/sbin/pppd` exits with error

See #210 for ideas on how to best handle this.

**Pull request closed without merging**
