### PR TITLE
Release

### PR DESCRIPTION
**Pull request by mrbaseman**
...and here the release commit in a separate PR

### CODE REVIEW

**Comment by adrienverge** [comment]
Thanks Martin!

Could you `git fetch origin && git rebase -i origin/master && git push -f` to keep only the last commit?

**Comment by adrienverge** [comment]
I allowed myself to do it myself and push-force to your branch to save some time.

**Comment by mrbaseman** [comment]
ah ok. I was wondering what's happening in the background ;)

**Comment by mrbaseman** [comment]
is there a problem with the travis-ci, because the checks still seem to fail?

**Comment by mrbaseman** [comment]
ah, found it. Indentation problem. Thanks for fixing that!

**Comment by adrienverge** [comment]
> ah ok. I was wondering what's happening in the background ;)

Hehe yeah, sorry about that!

> is there a problem with the travis-ci, because the checks still seem to fail?

Yes, there was a linting failure with one of the 3 security commits, but I fixed it in #546. It should be OK now.

Tag `v1.12.0` is created, I'll create packages for Fedora and CentOS.

**Pull request merged**
