### PR TITLE
set up routes correctly (pull request for #94)

### PR DESCRIPTION
**Pull request by mrbaseman**
This is a larger rework of the routing code, here a summary of the changes (for a detailed discussion see in issue #94 ):
- in ipv4_set_split_routes: add a host route to the gateway (basically copy&paste code from ipv4_set_default_routes)
- also in  ipv4_set_split_routes: merge in the two fixes for #25, namely add the gateway flag to these routes and corrected the test of the gateway ip (I have merged in pull request #88 here, for details see there). @adrienverge: if you want to merge this as a separate pull, please let me know and I can undo the changes in my branch.
- in ipv4_set_default_routes: change the route flag to host instead of gateway for the  route to the Fortigate. This is important when the existing default route is over a ppp device.
- in ipv4_restore_routes: remove the host route to the gateway which is now added in gateway mode, and free resources (just work that has to be done now that the above changes have been implemented).
- in ppp_interfaces_is_up: here are the changes from #90 which has already been merged. This actually was the starting point for the whole work. Since this is already upstream, these changes can be removed by rebase and squash of my whole pull request. I just did not do this yet, because I first thought that comments on the individual commits would stay intact, which was not the case.

### CODE REVIEW

**Comment by mrbaseman** [comment]
I just noticed that the comments which I have placed on the individual commits all showed up above, which didn't make much sense. So I have removed them. So maybe I should just rebase and squash?

**Comment by adrienverge** [comment]
Thanks @mrbaseman, this looks good!

Yes it's better to squash and have one commit for one logical change, but I would do it anyway before merging.

Most importantly, you need to explain the change *in the commit message itself*, so it is possible to understand why code changed by looking at the git history. This allows busting bugs more efficiently, avoid mistakes, enable useful `git blame`, etc. Also if this project moves from GitHub some day, we'll still have this information in git itself. (If you do a `git log` on this repo, you'll see that all non-trivial commits do this.)

About #88: do as you prefer, either include it as a separated commit here or wait for #88 to be merged.

**Comment by mrbaseman** [comment]
Hi @adrienverge,

I have rebased and squashed the pull request and added the above explanations to the commit message. I have also inserted a few comments from #90. I have kept the changes of #88 in this pull request because it is also part of the fix for the routing issues. I have also included my comments from there in the commit message.

**Comment by adrienverge** [comment]
Thanks!

**Pull request merged**
