### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by mrbaseman**

### CODE REVIEW

**Comment by mrbaseman** [comment]
sorry, this was already based on the branch that I have used in #489. Therefore the changes from that PR were doubled here. I have rebased it, so we can land the two requests independently, and rebase the other one after one of them has been merged.

**Comment by mrbaseman** [comment]
good point. It should not be much effort, just a few minor modifications at the end of `main.c`. I'll make another pull request for that.
I also have noticed that the man page could be rephrased a bit, just along the lines of the changes that I have made to `README.md` here. I'll push another commit for that.

**Comment by DimitriPapadopoulos** [comment]
Ooops... Sorry. I've mistakenly merged the pulll request without waiting for the man page changes. I can revert but it will probably be more messy than a new commit.

**Comment by mrbaseman** [comment]
no problem. I can add this in the upcoming pull request for the empty username/password topic

**Pull request merged**
