### PR TITLE
Add token-based one-time-password support

### PR DESCRIPTION
**Pull request by schlatterbeck**
See also issue #79

### CODE REVIEW

**Comment by adrienverge** [comment]
Hi @schlatterbeck, thanks, your code looks great.

I just have two questions:
- Do you have the possibility to try this with a regular VPN (no 2FA, no OTP), to check it does not break anything in these cases? (@dsgwork [reported](https://github.com/adrienverge/openfortivpn/issues/79#issuecomment-268520474) it works with his SMS-based 2FA VPN.)
- If after merging this change breaks anything for other users (especially ones that connect to older Fortinet VPN versions), will you fix it?

**Comment by schlatterbeck** [comment]
On Thu, Dec 22, 2016 at 12:02:29PM -0800, Adrien Verg� wrote:
> Hi @schlatterbeck, thanks, your code looks great.
> 
> I just have two questions:
> - Do you have the possibility to try this with a regular VPN (no 2FA,
> no OTP), to check it does not break anything in these cases? (@dsgwork
> [reported](https://github.com/adrienverge/openfortivpn/issues/79#issuecomment-268520474)

No, but I think this won't break anything for the following reason:

- The two-factor auth works like the normal auth with a user-chosen
  password in the first step. Only *after* this first step has completed
  my code kicks in.
- We used to compare the return code from the first auth step to http
  return-code 200 OK.
- The VPN requests the *second* authentication step (with the
  token-generated one-time password) by returning 401 Authorization
  Required instead of 200 OK after the first authentication.
- I've inserted a compare to 401 Authorization Required *before* the
  compare to 200 OK in Line 493 of http.c -- this should never match for
  one-factor authentication as this will return 200 OK after the first
  authentication step. Only at this point the new code is called.
- One possibility we *could* match 401 Auth Required here is if the user
  entered a wrong password (with only one-factor auth). My hunch was
  that maybe then the VPN could also return 401 Auth Required here. I've
  tested this and I'm getting a different return code with the message
  "No cookie given". I haven't instrumented the implementation to find
  out what http return code is returned here.

This leads me to believe the one-factor auth would work as normal but I
currently have no way to confirm this with a test.

> - If after merging this change breaks anything for other users
>   (especially ones that connect to older Fortinet VPN versions), will
>   you fix it?

Sure.

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   http://www.runtux.com
Reichergasse 131, A-3411 Weidling       email: office@runtux.com

**Comment by adrienverge** [comment]
Thanks Ralf

**Comment by mrbaseman** [comment]
Just for completeness: I have just tested the current master branch with a mobile token and client certificate (under Linux). It still works, so Ralfs code does not break anything, at least not for me.

**Comment by schlatterbeck** [comment]
On Tue, Jan 03, 2017 at 05:27:27AM -0800, Martin Hecht wrote:
> Just for completeness: I have just tested the current master branch
> with a mobile token and client certificate (under Linux). It still
> works, so Ralfs code does not break anything, at least not for me.

Thanks for the feedback!

Ralf
-- 
Dr. Ralf Schlatterbeck                  Tel:   +43/2243/26465-16
Open Source Consulting                  www:   http://www.runtux.com
Reichergasse 131, A-3411 Weidling       email: office@runtux.com

**Comment by adrienverge** [comment]
Thanks @mrbaseman!

**Pull request merged**
