### PR TITLE
SSO/SAML/2FA and external browser

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
A few notes on how to proceed in case SSO/SAML/2FA require user interaction in web pages containing JavaScript. The best course of action is to use external software that spawns a real web browser to retrieve the session cookie. Of course that requires a graphic session, unlike openfortivpn.

Related to #974, #1042, #1080.

### CODE REVIEW

**Review by adrienverge — APPROVED** [review]
Clear and helpful documentation is always welcome.

**Comment by DimitriPapadopoulos** [comment]
@peterhoeg Any comments on this addition to the README?

**Comment by peterhoeg** [comment]
Looks good - I just haven't tried it myself yet.

**Comment by filippor** [comment]
another script to retrieve token with external browser https://github.com/filippor/XdgOpenSaml

**Pull request merged**
