### PR TITLE
Added Ubuntu packages

### PR DESCRIPTION
**Pull request by ethchest**
In the main distribution for bionic and later, earlier with a ppa

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@ethchest Do you know of any any of accelerating the adoption of Debian packages by Ubuntu? As far as I can understand _openfortivpn_ needs to [move to _Debian unstable_](https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages) first. This is [now the case](https://packages.debian.org/sid/openfortivpn). Do we need to file a bug in Launchpad at this point?

**Comment by ethchest** [comment]
@DimitriPapadopoulos If you check the link in my commit, the package(s) are already part of bionic (18.04) I do not know whether this is related to Debian unstable. If you want to file a bug about the addition of openfortivpn to _earlier_ releases, this would have to be into backports and is quite unlikely in my opinion. (but you are of course welcome to try anyway, maybe I am wrong)

**Comment by ethchest** [comment]
Backports: https://wiki.ubuntu.com/UbuntuBackports

**Comment by DimitriPapadopoulos** [comment]
Ah my wrong. I had even installed it on my Ubuntu workstation!

Now the question is how to update the _openfortivpn_ Debian package to 1.7.1.

**Comment by ethchest** [comment]
Well, you are listed as secondary maintainer, so should be relatively easy, no? I do not know much about debian's procedures, but I guess filing a bug or writing on the mailing list (or writing the first maintainer directly) would be the way to go. Or opening a bug on launchpad and convincing ubuntu to upgrade without debian.

**Comment by DimitriPapadopoulos** [comment]
Filing a bug is probably the way to go.

**Comment by DimitriPapadopoulos** [comment]
Just found this **[intent to adopt](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902254)** on a Debian mailing list: the primary maintainer is requesting an adopter.

Unfortunately the relevant Git repo is dead (https://anonscm.debian.org/git/collab-maint/openfortivpn.git) and I'm afraid I won't have the time to re-start the whole process from scratch, especially since the mail-based Debian processes are extremely time-consuming for occasional users.

**Comment by DimitriPapadopoulos** [comment]
Following as [server migration](https://wiki.debian.org/Salsa/AliothMigration) the new repository for teh Debian package can be found here:
https://salsa.debian.org/debian/openfortivpn

**Comment by DimitriPapadopoulos** [comment]
I really don't understand the Debian packaging process:
1. I made a pull request to start updating the Debian package to 1.7.1: [Merge 1.7.1 from upstream ](https://salsa.debian.org/debian/openfortivpn/merge_requests/1) on July 3 at 7:17 PM server time,
2. Someone takes advantage of his member position to push his own changes on July 3, 11:06 PM server time. My pull request is now useless.
At least it's reassuring this member was given access to the _openfortivpn_ packaging project on July 3 at 4:02 PM server time, a few hours before my pull request.

**Comment by ethchest** [comment]
Sorry to hear about your troubles, but thanks for taking the time. Unfortunately, I will not be of much help I am afraid.

**Pull request merged**
