### PR TITLE
PPP exit status code

### LINKED ISSUE #797: PPP exit status code
PPP exit status codes should be reflected in _openfortivpn_ exit codes.

This is especially important when _openfortivpn_ is started as a service, PPP failures should be reported as _openfortivpn_ failures so that the service can be restarted. See #781.

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
* clean up PPP exit status code reporting
* propagate PPP exit status code to main()

Fixes #797.

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
@nikAizuddin Can you give this patch a try? Does it solve the problem raised in #781?

**Comment by nikAizuddin** [comment]
> 
> 
> @nikAizuddin Can you give this patch a try? Does it solve the problem raised in #781?

Noted, I'll try and will report back

**Comment by nikAizuddin** [comment]
Hi @DimitriPapadopoulos, the problem still the same. `openfortivpn` still exit with success after connection hangup.
```
Oct 27 18:21:45 rpizero systemd[1]: Started OpenFortiVPN for client.
Oct 27 18:21:45 rpizero openfortivpn[2292]: INFO:   Connected to gateway.
Oct 27 18:21:45 rpizero openfortivpn[2292]: INFO:   Authenticated.
Oct 27 18:21:45 rpizero openfortivpn[2292]: INFO:   Remote gateway has allocated a VPN.
Oct 27 18:21:46 rpizero pppd[2297]: pppd 2.4.7 started by root, uid 0
Oct 27 18:21:46 rpizero pppd[2297]: Using interface ppp0
Oct 27 18:21:46 rpizero openfortivpn[2292]: Using interface ppp0
Oct 27 18:21:46 rpizero pppd[2297]: Connect: ppp0 <--> /dev/pts/2
Oct 27 18:21:46 rpizero openfortivpn[2292]: Connect: ppp0 <--> /dev/pts/2
Oct 27 18:21:46 rpizero openfortivpn[2292]: INFO:   Got addresses: [*.*.*.*], ns [8.8.8.8, 8.8.4.4]
Oct 27 18:21:46 rpizero openfortivpn[2292]: INFO:   Negotiation complete.
Oct 27 18:21:49 rpizero openfortivpn[2292]: INFO:   Negotiation complete.
Oct 27 18:21:49 rpizero pppd[2297]: local  IP address *.*.*.*
Oct 27 18:21:49 rpizero openfortivpn[2292]: local  IP address *.*.*.*
Oct 27 18:21:49 rpizero openfortivpn[2292]: remote IP address *.*.*.*
Oct 27 18:21:49 rpizero pppd[2297]: remote IP address *.*.*.*
Oct 27 18:21:49 rpizero openfortivpn[2292]: INFO:   Interface ppp0 is UP.
Oct 27 18:21:49 rpizero openfortivpn[2292]: INFO:   Setting new routes...
Oct 27 18:21:49 rpizero openfortivpn[2292]: INFO:   Adding VPN nameservers...
Oct 27 18:21:49 rpizero openfortivpn[2292]: INFO:   Tunnel is up and running.
Oct 28 02:21:49 rpizero openfortivpn[2292]: INFO:   Cancelling threads...
Oct 28 02:21:49 rpizero openfortivpn[2292]: INFO:   Cleanup, joining threads...
Oct 28 02:21:49 rpizero openfortivpn[2292]: INFO:   Setting ppp0 interface down.
Oct 28 02:21:49 rpizero openfortivpn[2292]: INFO:   Restoring routes...
Oct 28 02:21:49 rpizero openfortivpn[2292]: INFO:   Removing VPN nameservers...
Oct 28 02:21:50 rpizero pppd[2297]: Hangup (SIGHUP)
Oct 28 02:21:50 rpizero openfortivpn[2292]: Hangup (SIGHUP)
Oct 28 02:21:50 rpizero openfortivpn[2292]: Connect time 480.1 minutes.
Oct 28 02:21:50 rpizero openfortivpn[2292]: Sent 145057166 bytes, received 271520973 bytes.
Oct 28 02:21:50 rpizero pppd[2297]: Connect time 480.1 minutes.
Oct 28 02:21:50 rpizero pppd[2297]: Sent 145057166 bytes, received 271520973 bytes.
Oct 28 02:21:50 rpizero pppd[2297]: Modem hangup
Oct 28 02:21:50 rpizero openfortivpn[2292]: Modem hangup
Oct 28 02:21:50 rpizero openfortivpn[2292]: Connection terminated.
Oct 28 02:21:50 rpizero pppd[2297]: Connection terminated.
Oct 28 02:21:50 rpizero pppd[2297]: Exit.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   pppd: The link was terminated by the modem hanging up.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   Terminated pppd.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   Closed connection to gateway.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   Logged out.
Oct 28 02:21:50 rpizero systemd[1]: openfortivpn@client.service: Succeeded.
```

Output for `sudo systemctl status openfortivpn@client.service`:
```
● openfortivpn@client.service - OpenFortiVPN for client
   Loaded: loaded (/lib/systemd/system/openfortivpn@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:openfortivpn(1)

Oct 28 02:21:50 rpizero pppd[2297]: Modem hangup
Oct 28 02:21:50 rpizero openfortivpn[2292]: Modem hangup
Oct 28 02:21:50 rpizero openfortivpn[2292]: Connection terminated.
Oct 28 02:21:50 rpizero pppd[2297]: Connection terminated.
Oct 28 02:21:50 rpizero pppd[2297]: Exit.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   pppd: The link was terminated by the modem hanging up.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   Terminated pppd.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   Closed connection to gateway.
Oct 28 02:21:50 rpizero openfortivpn[2292]: INFO:   Logged out.
Oct 28 02:21:50 rpizero systemd[1]: openfortivpn@client.service: Succeeded.
```

I already add `Restart=on-failure` in `/lib/systemd/system/openfortivpn@.service` and the service doesn't restart after the hangup:
```
[Unit]
Description=OpenFortiVPN for %I
After=network-online.target
Documentation=man:openfortivpn(1)

[Service]
Type=simple
PrivateTmp=true
ExecStart=/usr/local/bin/openfortivpn -c /etc/openfortivpn/%I.conf
OOMScoreAdjust=-100
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by DimitriPapadopoulos** [comment]
Can you check the exit status code of `openfortivpn` in your case? Add a _log_info()_ here:
https://github.com/adrienverge/openfortivpn/blob/c3ae8b9/src/main.c#L642

I'm not certain what _systemd_ expects and how it interprets `openfortivpn` exit status codes.

**Comment by nikAizuddin** [comment]
> Can you check the exit status code of openfortivpn in your case? Add a log_info() here:
https://github.com/adrienverge/openfortivpn/blob/c3ae8b9/src/main.c#L642

Alright, I'll try again with `log_info()`

**Comment by DimitriPapadopoulos** [comment]
Oh wait. This error:
```
The link was terminated by the modem hanging up.
```
is precisely error 16 which I consider a synonym of success:
https://github.com/DimitriPapadopoulos/openfortivpn/blob/1bd255a/src/tunnel.c#L459

Why? Just because there used to be this comment:
https://github.com/adrienverge/openfortivpn/blob/c3ae8b9/src/tunnel.c#L409
Perhaps it should **not** be considered a synonym of success. Not sure how to interpret it actually. Anyone?

**Comment by DimitriPapadopoulos** [comment]
Do you know why does `openfortivpn` exits in your case?

**Comment by DimitriPapadopoulos** [comment]
You should probably remove this `case 16` stuff and test again:
https://github.com/DimitriPapadopoulos/openfortivpn/blob/1bd255a/src/tunnel.c#L459-L463

**Comment by nikAizuddin** [comment]
> Do you know why `openfortivpn` exits in your case?

I'm not sure. But I'll try ask my admins.

> You should probably remove this `case 16` stuff and test again:
> https://github.com/DimitriPapadopoulos/openfortivpn/blob/1bd255a/src/tunnel.c#L459-L463

Noted

**Comment by DimitriPapadopoulos** [comment]
The thing is, I also get error 16 `The link was terminated by the modem hanging up` when leaving _openfortivpn_ with Ctrl+C. So the exit status code of PPP by itself is nor really telling us whether `openfortivpn` exits "normally" or dies because of an error condition.

**Comment by DimitriPapadopoulos** [comment]
I could test _get_sig_received()_ in addition to the PPP exit status and decide that `SIGINT` and `SIGTERM` mean no error, whatever the PPP exit status code.

**Comment by nikAizuddin** [comment]
> Do you know why `openfortivpn` exits in your case?

I have asked my admins. Config `set auth-timeout 28800` was applied on the FortiGate VPN server.

Description for the `auth-timeout`:
```
The auth-timeout is period of time in seconds that the SSL VPN will wait before re-authentication is enforced.
Default value is 28800 seconds (8 hours). Range: <0> to <259200>
```

Now we try to `set auth-timeout 0` (no timeout).

**Comment by DimitriPapadopoulos** [comment]
Good, 1 is `EXIT_FAILURE`which mean that _systemd_ should restart _openfortivpn_.

The problem remains that `pppd` also returns 16 when interrupting _openfortivpn_ with Ctrl+C. But in that case I wouldn't want to return `EXIT_FAILURE` too.

**Review by mrbaseman — APPROVED** [review]
Hi Dimitri, 
this looks good to me. Unfortunately, I didn't find the time to review it earlier. Sorry.
Best regards, Martin

**Comment by DimitriPapadopoulos** [comment]
Changed to return  `EXIT_SUCCESS` instead of `EXIT_FAILURE` when `openfortivpn`/`pppd` stop after Ctrl+C (**`SIGINT`**) or `kill -15` (**`SIGTERM`**).

**Comment by taufikterdidik** [comment]
systemctl restart on-failure often works, but sometime, it stuck and it not worked. this is my log when it not worked.

`pi@rumah:~ $ sudo systemctl status --no-pager --full openfortivpn@uny.service 
● openfortivpn@uny.service - OpenFortiVPN for uny
   Loaded: loaded (/etc/systemd/system/openfortivpn@uny.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-03-23 20:23:04 WIB; 5h 42min ago
     Docs: man:openfortivpn(1)
  Process: 6216 ExecStartPost=/home/pi/sharenet.sh enable (code=exited, status=0/SUCCESS)
 Main PID: 6215 (openfortivpn)
    Tasks: 1 (limit: 1173)
   CGroup: /system.slice/system-openfortivpn.slice/openfortivpn@uny.service
           └─6215 /usr/local/bin/openfortivpn -c /etc/openfortivpn/uny.conf

Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Cleanup, joining threads...
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Setting ppp0 interface down.
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Restoring routes...
Mar 24 01:01:54 rumah openfortivpn[6215]: WARN:   Could not delete route through tunnel (No such device).
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Removing VPN nameservers...
Mar 24 01:01:54 rumah openfortivpn[6215]: Too few arguments.
Mar 24 01:01:54 rumah openfortivpn[6215]: Too few arguments.
Mar 24 01:01:54 rumah openfortivpn[6215]: ERROR:  pppd: The link was terminated by the modem hanging up.
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Terminated pppd.
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Closed connection to gateway.


pi@rumah:~ $ sudo journalctl -u openfortivpn@uny.service --since today
-- Logs begin at Tue 2021-03-23 06:19:20 WIB, end at Wed 2021-03-24 02:06:23 WIB. --
Mar 24 01:01:47 rumah pppd[6221]: No response to 4 echo-requests
Mar 24 01:01:47 rumah openfortivpn[6215]: No response to 4 echo-requests
Mar 24 01:01:47 rumah openfortivpn[6215]: Serial link appears to be disconnected.
Mar 24 01:01:47 rumah openfortivpn[6215]: Connect time 278.6 minutes.
Mar 24 01:01:47 rumah openfortivpn[6215]: Sent 10742211 bytes, received 181050981 bytes.
Mar 24 01:01:47 rumah pppd[6221]: Serial link appears to be disconnected.
Mar 24 01:01:47 rumah pppd[6221]: Connect time 278.6 minutes.
Mar 24 01:01:47 rumah pppd[6221]: Sent 10742211 bytes, received 181050981 bytes.
Mar 24 01:01:53 rumah pppd[6221]: Connection terminated.
Mar 24 01:01:53 rumah openfortivpn[6215]: Connection terminated.
Mar 24 01:01:53 rumah pppd[6221]: Modem hangup
Mar 24 01:01:53 rumah openfortivpn[6215]: Modem hangup
Mar 24 01:01:53 rumah pppd[6221]: Exit.
Mar 24 01:01:53 rumah openfortivpn[6215]: ERROR:  read: Input/output error
Mar 24 01:01:53 rumah openfortivpn[6215]: INFO:   Cancelling threads...
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Cleanup, joining threads...
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Setting ppp0 interface down.
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Restoring routes...
Mar 24 01:01:54 rumah openfortivpn[6215]: WARN:   Could not delete route through tunnel (No such device).
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Removing VPN nameservers...
Mar 24 01:01:54 rumah openfortivpn[6215]: Too few arguments.
Mar 24 01:01:54 rumah openfortivpn[6215]: Too few arguments.
Mar 24 01:01:54 rumah openfortivpn[6215]: ERROR:  pppd: The link was terminated by the modem hanging up.
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Terminated pppd.
Mar 24 01:01:54 rumah openfortivpn[6215]: INFO:   Closed connection to gateway.`

how can I solve this? thanks

**Comment by DimitriPapadopoulos** [comment]
@taufikterdidik Please open a new issue. This is a closed pull request.

**Pull request merged**
