### PR TITLE
openfortivpn version 1.17.2

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by adrienverge** [comment]
Looks good to me! Just undraft the PR when you want me to merge and tag it.

And thanks for all the recent work Dimitri.

**Comment by DimitriPapadopoulos** [comment]
@adrienverge Can you have a look at the changelog and make sure it's clear/detailed enough?

**Comment by adrienverge** [comment]
Looks good to me. Let's go for a release?

**Comment by DimitriPapadopoulos** [comment]
Yes, let's release 1.17.2.

**Comment by adrienverge** [comment]
Thanks for the work @DimitriPapadopoulos!

**Pull request merged**
