### PR TITLE
allow logging in with a certificate only

### PR DESCRIPTION
**Pull request by mrbaseman**
...and with password set to an empty string, which denotes that no password shall be asked or sent
allow username to be empty for smartcard login
update man page and readme

### CODE REVIEW

**Comment by mrbaseman** [comment]
In #491 we were discussing if a dummy username is really needed. 

I had a similar branch in my repo for testing in the context of #375 

Although we didn't reach a final solution there, we could merge those lines, together with a few modifications that I have already squashed in so that we don't require dummy variables for the smartcard login.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos could you run Coverity again on this PR, please? To make sure we don't introduce new defects right after we have cleaned up everything

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman There are a few warnings about _printf()_ that are easy to fix but I'm puzzled by the other errors: have they been introduced by the new code or had they been previously missed by Coverity?

**Comment by mrbaseman** [comment]
the [new changes](https://github.com/adrienverge/openfortivpn/pull/493/files) aren't that big. Could it be that Coverity stops when it has found a certain amount of issues or one with a high-enough criticality-value? Or it randomly takes different branches for the evaluation in each run?

I'll try to solve them and push further commits to this PR. Once they are fixed we'll have to see how we squash the commits into two ones (one for the current topic of this PR and another one for the Coverity fixes).

**Comment by mrbaseman** [comment]
Oh, this scan was not on the current branch. The fix for CID349832 [is already in my cert-only branch](https://github.com/mrbaseman/openfortivpn/blob/4a2848660ce1758385887048ec030f31d4a8c90b/src/userinput.c#L46). I have rebased that branch and force-pushed it to my account. Maybe you (or Coverity) have to (force-)pull again?

**Comment by DimitriPapadopoulos** [comment]
Coverity scans have to be started manually - automatic runs are triggerred by commits to the adrienverge/coverity_scan branch as suggested by the Coverity documentation.

**Comment by DimitriPapadopoulos** [comment]
Much better now: 0 defects!

**Comment by DimitriPapadopoulos** [comment]
I suggest you merge.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos  how is the `adrienverge/coverity_scan` branch updated? Can I push directly to that branch? Or can I make a pull request from master into that branch?

**Comment by DimitriPapadopoulos** [comment]
I think you can merge `adrienverge/master` directly into `adrienverge/coverity_scan` - only `adrienverge/master` is protected. As far as I can recall this is what I had been applying:
[What is the best (and safest) way to merge a Git branch into master?](https://stackoverflow.com/questions/5601931/what-is-the-best-and-safest-way-to-merge-a-git-branch-into-master)

**Comment by mrbaseman** [comment]
This went into the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0).

**Pull request merged**
