### PR TITLE
modify README.md (modify dependencies, etc)

### PR DESCRIPTION
**Pull request by Mabin-J**
- fix indent
- modify dependencies
- add some decoration

### CODE REVIEW

**Comment by mrbaseman** [comment]
could you squash these commits, please, so that we have a single transaction in this PR?

**Comment by Mabin-J** [comment]
OK. I'll squash that.

I think that two commit's checkpoint is different so I didn't squash.
(but 4bb5062 isn't same rule... that my fault. sorry.)

**Comment by mrbaseman** [comment]
If you want #128 in here, could you please update the configure command line and the example sudo configuration and squash once more?

**Comment by Mabin-J** [comment]
Oh, it's my mistake. I added description about #128 in commit message but I didn't add file...  :sweat_smile:

**Comment by mrbaseman** [comment]
thanks, applied. I personally would put the configuration into /usr/local/etc then, but that would be the default for sysconfdir and theconfigure option could be dropped. So I decided to keep the configuration in /etc so that we have this option, which many users might find useful, in the examples.

**Comment by Mabin-J** [comment]
I saw that put config file into /usr/local/etc and make symbolic link into /etc. 
But I don't know which way is common.

**Comment by mrbaseman** [comment]
I'd say the default is that the sysconfig directory should be $prefix/etc. However, in some applications it is hard-coded as /etc, while the install script puts the configuration into $prefix/etc. In that case, a symlink in /etc pointing to the real location of the configuration would be a workaround. However, the better solution would be to set the location at configure time for both, the install script and for the program (btw, for openfortivpn #76 was about this topic)

**Pull request merged**
