### PR TITLE
use ppp interface name instead of ip for routing

### PR DESCRIPTION
**Pull request by mrbaseman**
on FreeBSD (and OSX), namely when adding routes via route command

### CODE REVIEW

**Comment by mrbaseman** [comment]
With 5875f03 I have tested this successfully on Mac OSX. 
The problem was that on OSX a second _default_ route is added, which is needed for the ppp link. `ipv4_get_route()` has found that one and removed it by mistake. 
For completeness we should also check the netmask. I'll push another commit.

**Comment by mrbaseman** [comment]
I have successfully tested on Ubuntu, OSX and FreeBSD, now.

**Comment by mrbaseman** [comment]
I have squashed the commits on this branch

**Comment by mrbaseman** [comment]
I have added another detail here: On Mac OSX and FreeBSD the debug output was really huge because the whole routing table and all parsing results for each line were included. Now it's only printed when the `-v` option is used twice.

@DimitriPapadopoulos @adrienverge Ok to merge this one? 

I would not squash these commits, because it's two separate things, but both about OSX and BSD, therefore I have chosen to push c79879e into the same branch.

**Comment by adrienverge** [comment]
About the change, I trust you, so I let you and Dimitri decide what's best.

About the commits, you're right to avoid squashing them if they are two different changes. However if you want you can drop the third commit (merge commit) by clicking "Rebase and merge" instead of "Merge", or in command-line by rebasing on `origin/master` and `push -f`.

**Comment by mrbaseman** [comment]
I have rebased this on the current master. The third commit is new now. I have noticed that I abuse the "packet logging level" in 725cb18 for the netstat parsing output, so a more general name for this constant seems appropriate.
@DimitriPapadopoulos do you have any remarks on this? Otherwise I would like to apply this one and tag the new release in #393

**Comment by mrbaseman** [comment]
I have successfully re-tested on Ubuntu 12.04, 16.04, 18.04, MacOS X 10.11, and FreeBSD 11.2.

**Pull request merged**
