### PR TITLE
Update ipv4.c

### PR DESCRIPTION
**Pull request by jon2kx**
This should fix a ton of the issues that come up in https://github.com/adrienverge/openfortivpn/issues/154

Please look over my work, I'm new in C programming, I've been a shell and python and perl guy most of my career.

### CODE REVIEW

**Comment by jon2kx** [comment]
0.02s$ make -C $HOME/astyle/build/gcc prefix=$HOME install
make: Entering directory `/home/travis/astyle/build/gcc'
install -o travis -g travis -m 755 -d /home/travis/bin
install -o travis -g travis -m 755 -d /home/travis/share/doc/astyle
make: Leaving directory `/home/travis/astyle/build/gcc'
0.33s$ ./tests/lint/run.sh
error: src/ipv4.c does not comply with coding style
diff --git a/src/ipv4.c b/tmp/tmp.BO1sP4rRcY
index 57d58ca..7e488ea 100644
--- a/src/ipv4.c
+++ b/tmp/tmp.BO1sP4rRcY
@@ -139 +139 @@ static int ipv4_get_route(struct rtentry *route)
-	char *saveptr3 = NULL;	
+	char *saveptr3 = NULL;

I 'm not sure where I am missing the coding style , I've checked a few times now, I'm new to C, any help in getting this would be appreciated.

**Comment by adrienverge** [comment]
GitHub is showing the problem to you ;-)
problem

By the way you can run linting scripts locally to identify the problem.

**Comment by DimitriPapadopoulos** [comment]
Which OS does this patch target exactly?

**Comment by jon2kx** [comment]
@adrienverge  Thanks for that, the build passes now. 

So I saw your comments about just calling netstat, I assumed that it was called with system() at some point down the line here. 

@DimitriPapadopoulos non-macintosh unix/linux/bsd systems.

**Comment by DimitriPapadopoulos** [comment]
This part of the code is not executed on non-macintosh unix/linux/bsd systems - hence there isn't anything to fix here.

The "Input/output errors" are unrelated to `netstat`.

**Comment by jon2kx** [comment]
#ifndef __APPLE__
	int fd;
	// Cannot stat, mmap not lseek this special /proc file
	fd = open("/proc/net/route", O_RDONLY);
	if (fd == -1)
		return ERR_IPV4_SEE_ERRNO;

	size = read(fd, buffer, sizeof(buffer) - 1);
	if (size == -1) {
		close(fd);
		return ERR_IPV4_SEE_ERRNO;
	}
	close(fd);
#else
	FILE *fp;
	FILE *wnst;
	int len = sizeof(buffer) - 1;
	char *saveptr3 = NULL;

	// Open the command for reading
	wnst = popen("which netstat");
	fp = popen("wnst -f inet -rn", "r");
	if (fp == NULL)
return ERR_IPV4_SEE_ERRNO;

Please excuse me if I have this incorrect, but if the __APPLE__ token is set, this previous block of code executes, else the applicable block is executed? 

Do I have this incorrect, can you help me understand if I have this incorrect?

**Comment by DimitriPapadopoulos** [comment]
These mutliple `ifdef`/`ifndef` occurrence are indeed confusing (notice the missing/extra **n**):
* some of them use `ifdef __APPLE__` (_if on Apple_)
* other use `ifndef __APPLE__` (_if **not** on Apple_)

Ideally the code should be rewritten using `ifdef __APPLE__` only for the sake of clarity.

**Comment by jon2kx** [comment]
@DimitriPapadopoulos  Thank you for helping me understand. I appreciate your time.

**Pull request closed without merging**
