### PR TITLE
Update readme for install with MacPorts

### PR DESCRIPTION
**Pull request by millerdev**
Submitted to MacPorts https://trac.macports.org/ticket/56121

### CODE REVIEW

**Comment by adrienverge** [comment]
Hi, thanks for submitting to MacPorts.

But why do you want to store this `Portfile` here?

**Comment by millerdev** [comment]
So it can be maintained and updated as new versions are released. Feel free to drop the Portfile from this PR if you don't want it.

**Comment by adrienverge** [comment]
Yes I think it's better to drop it. Other package files (for Fedora, Debian, Ubuntu...) are also stored elsewhere.

**Comment by DimitriPapadopoulos** [comment]
Here is an example of a re-organized README.md:
https://github.com/DimitriPapadopoulos/openfortivpn/blob/installing/README.md

Does it help?

**Comment by millerdev** [comment]
Yes, I noticed that. Your version is much better. Updated.

**Comment by DimitriPapadopoulos** [comment]
If you're OK with the above, I can squash into a single commit myself if it helps.

**Comment by millerdev** [comment]
> Also you do realize that you suggest using only Homebrew and not MacPorts for building from sources, don't you?

Yes. The MacPorts build-from-source instructions were exactly the same as above install-with-MacPorts instructions, so it seemed redundant to me.

**Comment by millerdev** [comment]
Squashed. Maybe wait for the [Portfile](https://trac.macports.org/ticket/56121) be added to MacPorts repos before merging?

**Comment by DimitriPapadopoulos** [comment]
Sure, just add a comment when it's ready.

**Comment by millerdev** [comment]
Portfile added to MacPorts: https://github.com/macports/macports-ports/pull/2026

**Comment by mrbaseman** [comment]
@millerdev can you trigger an update of the Portfile? We have released _openfortivpn_ with some fixes in the routing code for OSX.

**Comment by millerdev** [comment]
@mrbaseman https://github.com/macports/macports-ports/pull/3130

**Pull request merged**
