### PR TITLE
CodeQL Analysis

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Security analysis from GitHub for C, C++, C#, Java, JavaScript, TypeScript, Python, and Go developers.

### CODE REVIEW

**Comment by adrienverge** [comment]
I've allowed myself to force-push to your branch, to see if the new GitHub Actions work. It seems that they do :)

**Comment by DimitriPapadopoulos** [comment]
Is it worth adding CodeQL / Analyze as a first layer run on every pull request, in addition to Coverity Scan which cannot be run on each pull request?

**Comment by adrienverge** [comment]
I don't really know about CodeQL, but it looks to me like more code scanning cannot hurt. @mrbaseman do you have an opinion on this?

@DimitriPapadopoulos do you know why the feedback says "1 analysis not found"?
results

**Comment by DimitriPapadopoulos** [comment]
My guess was that's because it's not yet integrated in the mason branch.

**Pull request merged**
